#!/usr/bin/env python3
"""Freeze exact application labels; --check refuses drift at manual build time."""
from pathlib import Path
import sys
import re

here = Path(__file__).resolve().parent
source = here.parent.parent / 'assets/ui-translations.tsv'
out = ['% Generated by labels.py from assets/ui-translations.tsv; do not edit.']
for line in source.read_text().splitlines():
    if not line or line.startswith('#'):
        continue
    key, *values = line.split('|')
    for lang, value in zip(('en', 'de', 'bg'), values):
        assert not any(c in value for c in '\\{}%&#_$'), value
        out.append(r'\expandafter\def\csname ui@' + lang + '@' + key + r'\endcsname{' + value + '}')
expected = '\n'.join(out) + '\n'
target = here / 'ui-labels.tex'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != expected:
        sys.exit('UI labels changed. Review manual procedures, then run python3 docs/manual/labels.py.')
    keys = {line.split('|')[0] for line in source.read_text().splitlines()
            if line and not line.startswith('#')}
    order = None
    for lang in ('de', 'en', 'bg'):
        body = (here / (lang + '.tex')).read_text()
        missing = set(re.findall(r'\\UI\{([^}]+)\}', body)) - keys
        if missing:
            sys.exit(f'{lang}: unknown UI labels: {missing}')
        pages = re.findall(r'\\page\{([^}]+)\}\{([^}]+)\}', body)
        if order is not None and pages != order:
            sys.exit(f'{lang}: chapter order differs from the other languages')
        order = pages
else:
    target.write_text(expected)
