#!/usr/bin/env python3
"""Regenerate the immutable font atlas; Pillow with libraqm + fontTools required.
Source: playbeing/dinish a5f3b2a3b932336225815bf9005e3b72cc3de71c (OFL).
Bulgarian glyphs use OpenType locl with language=bg, never Russian fallback.
"""
from pathlib import Path
import sys
import json
root=Path(__file__).resolve().parent.parent
chars=sorted(set(chr(x) for x in range(32,127)) | set('ÄÖÜäöüß') | set(chr(x) for x in range(0x410,0x450)) | set('Ѝѝ'))
if "--strings-only" not in sys.argv:
    from PIL import Image, ImageDraw, ImageFont, features
    from fontTools.ttLib import TTFont
    font=root/'assets/fonts/DINishCondensed-SemiBold.ttf'
    assert features.check('raqm')
    cmap=TTFont(font).getBestCmap()
    assert all(ord(c) in cmap for c in chars)
    rows=[]; data=[]
    for size in (16,20,24,28,32,40,48):
        f=ImageFont.truetype(str(font),size,layout_engine=ImageFont.Layout.RAQM)
        for char in chars:
            kw=dict(language='bg',features=['-kern','-liga'])
            box=f.getbbox(char,anchor='lt',**kw)
            w,h=box[2]-box[0],box[3]-box[1]
            im=Image.new('L',(max(1,w),max(1,h)))
            ImageDraw.Draw(im).text((-box[0],-box[1]),char,font=f,fill=255,anchor='lt',**kw)
            raw=bytes(im.getdata()) if w*h else b''
            # Quantized 4-bit alpha run lengths; deterministic and small on SYSTEM.
            vals=[(p+8)//17 for p in raw]; packed=[]
            for val in vals:
                if packed and packed[-1][1]==val and packed[-1][0]<16: packed[-1][0]+=1
                else: packed.append([1,val])
            offset=len(data); data.extend((n-1)*16+v for n,v in packed)
            baseline=f.getbbox(char,anchor='ls',**kw)
            rows.append((size,ord(char),int(round(f.getlength(char,**kw))),w,h,box[0],baseline[1],offset,len(packed)))
            assert char==' ' or any(vals),char
    # Verify native lowercase forms differ from default Cyrillic.
    f=ImageFont.truetype(str(font),32)
    assert bytes(f.getmask('бгдпт',language='bg')) != bytes(f.getmask('бгдпт',language='ru')), 'Bulgarian locl missing'
    out=['// Generated by scripts/build-ui-font.py. DINish under assets/fonts/OFL.txt.','#pragma once','namespace ui_font {','struct Glyph {int size,code,advance,w,h,left,top,offset,length;};','inline constexpr Glyph glyphs[] = {']
    out += ['{'+','.join(map(str,r))+'},' for r in rows]
    out += ['};','inline constexpr unsigned char pixels[] = {']
    out += [','.join(map(str,data[i:i+100]))+',' for i in range(0,len(data),100)]
    out += ['};','}']
    (root/'include/voider_ui_font.hpp').write_text('\n'.join(out)+'\n')
import re
operation_keys=set()
for source in ('src/voider_main.cpp','src/voider_ui.cpp'):
    for match in re.finditer(r'operation\([^;]+;', (root/source).read_text()):
        operation_keys.update(re.findall(r'"([A-Z][A-Z ?]+)"',match[0]))
installer=(root/'src/voider_install.cpp').read_text()
factory_states={('INSTALLING',key) for key in re.findall(r'install_status\("INSTALLING","([^"]+)"',installer)}
factory_states |= {('FAILED',key) for key in re.findall(r'install_fail\([^,]+,"([^"]+)"',installer)}
factory_states |= {('INSTALLING','STARTING'),('FAILED','SEE INSTALL LOG'),('COMPLETE','REBOOT FAILED')}
operation_states=set()
for source in ('src/voider_main.cpp','src/voider_ui.cpp'):
    # Pairing failure cleanup owns the status write; retain each call's message.
    operation_states.update(('failed', key) for key in re.findall(
        r'\bfail\([^,]+,"([A-Z ?]+)"', (root/source).read_text()))
    for match in re.finditer(r'operation\("(working|failed|done|remove)",([^;]+);', (root/source).read_text()):
        operation_states.update((match[1],key) for key in re.findall(r'"([A-Z][A-Z ?]+)"',match[2]))
    for match in re.finditer(r'operation\(rc\?"([a-z]+)":"([a-z]+)",rc\?"([A-Z ]+)":"([A-Z ]+)"', (root/source).read_text()):
        operation_states.update(((match[1],match[3]),(match[2],match[4])))
ui=(root/'src/voider_ui.cpp').read_text()
operation_states.update(('failed',key) for key in re.findall(r'result\("([A-Z ]+)"',ui))
scan=ui.split('static std::string scan_error(',1)[1].split('static int command_status',1)[0]
operation_states.update(('failed',key) for key in re.findall(r'return "([A-Z ]+)"',scan))
usb_errors=(root/'src/voider_main.cpp').read_text().split('static std::string usb_error(',1)[1].split('static int language_save',1)[0]
operation_states.update(('failed',key) for key in re.findall(r'"([A-Z][A-Z ]+)"',usb_errors))
operation_states.update({('failed','ACTION FAILED'),('done','COMPLETE')})
operation_states.update({('failed','PHONE CABLE'),('failed','NO INTERNET'),('failed','NETWORK READY'),('done','NETWORK READY')})
operation_keys.update(key for _,key in operation_states)
translations=[]
for line in (root/'assets/ui-translations.tsv').read_text().splitlines():
    if not line or line.startswith('#'):continue
    row=line.split('|'); assert len(row)==4,line
    assert all(c in chars for text in row[1:] for c in text),row
    translations.append(row)
    if row[0][:1].islower() or row[0]=='OpenRC service enablement': factory_states.add(('FAILED',row[0]))
out=['// Generated from assets/ui-translations.tsv. All languages resident in RAM.','#pragma once','#include <array>','#include <map>','#include <string>','inline const std::map<std::string,std::array<std::string,3>> ui_strings = {']
out += ['{'+json.dumps(r[0])+',{'+','.join(json.dumps(s,ensure_ascii=False) for s in r[1:])+'}},' for r in translations]
out+=['};']
for name,states in [('ui_factory_states',factory_states),('ui_operation_states',operation_states)]:
    out+=['inline const std::array<std::pair<std::string,std::string>,'+str(len(states))+'> '+name+' = {{'+','.join('{'+json.dumps(a)+','+json.dumps(b)+'}' for a,b in sorted(states))+'}};']
out+=['inline const std::array<std::string,'+str(len(operation_keys))+'> ui_operation_keys = {{'+','.join(json.dumps(k) for k in sorted(operation_keys))+'}};']
assert {key for _,key in factory_states} <= {r[0] for r in translations}
assert operation_keys <= {r[0] for r in translations}, operation_keys-{r[0] for r in translations}
(root/'include/voider_ui_strings.hpp').write_text('\n'.join(out)+'\n')
print(f'translations={len(translations)}')
