// voider-dhcp: fixed single-lease DHCP helper for the phone port.
//
// This is not a pool. It offers exactly 172.16.19.85 on the two-host /30 link
// where voider itself is 172.16.19.86. The fixed lease makes the phone display
// and troubleshooting deterministic.

#include <filesystem>
#include <fstream>
#include <iostream>
#include "voider_util.hpp"
namespace fs=std::filesystem;
static Cfg C;
static int write_conf(){
    fs::create_directories(fs::path(C.dhcp_conf).parent_path());
    fs::create_directories(fs::path(C.dhcp_leases).parent_path());
    std::ofstream(C.dhcp_leases,std::ios::app).close();
    std::ofstream f(C.dhcp_conf);
    f<<"# generated by voider-dhcp\ninterface "<<C.phone_if<<"\nstart "<<C.dhcp_start<<"\nend "<<C.dhcp_end
    <<"\noption subnet "<<C.dhcp_netmask<<"\noption router "<<C.dhcp_router<<"\noption dns "<<C.dhcp_dns
    <<"\noption lease "<<C.dhcp_lease_sec<<"\nlease_file "<<C.dhcp_leases<<"\npidfile "<<C.dhcp_pid
    <<"\nauto_time 0\nremaining yes\n";
    return 0;
}
static int start(){
    if(!C.dhcp_enabled){
        std::cout<<"DHCP_DISABLED\n";
        return 0;
    }
    write_conf();
    vu::run("ip addr replace "+C.phone_gw+"/"+std::to_string(C.dhcp_cidr)+" dev "+C.phone_if);
    vu::run("ip link set "+C.phone_if+" up");
    std::string pid=vu::read1(C.dhcp_pid);
    if(!pid.empty()&&std::system(("kill -0 "+pid+" 2>/dev/null").c_str())==0)return 0;
    fs::remove(C.dhcp_pid);
    return vu::run("udhcpd -S "+vu::shq(C.dhcp_conf));
}
static int status(){
    std::cout<<"DHCP_ENABLED "<<C.dhcp_enabled<<"\nPHONE_IF "<<C.phone_if<<"\nRANGE "<<C.dhcp_start<<" "<<C.dhcp_end
    <<"\nROUTER "<<C.dhcp_router<<"\nCIDR "<<C.dhcp_cidr<<"\nNETMASK "<<C.dhcp_netmask
    <<"\nFIXED_ONLY yes\nCONF "<<C.dhcp_conf<<"\nLEASES "<<C.dhcp_leases<<"\n";
    return 0;
}
int main(int ac,char**av){
    C=cfg();
    std::string c=ac>1?av[1]:"status";
    if(c=="write")return write_conf();
    if(c=="start")return start();
    if(c=="status")return status();
    std::cerr<<"usage: voider-dhcp start|write|status\n";
    return 2;
}
