#include <array>
#include <cstdlib>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include "voider_config.hpp"
#include "voider_util.hpp"

using vu::read1;
using vu::run;
using vu::shq;

namespace fs=std::filesystem;
static Cfg C;
static void ensure_server_wg0_key(){
    fs::create_directories("/etc/voider/private");
    if(!fs::exists("/etc/voider/private/wg0.key")){
        run("wg genkey | tee /etc/voider/private/wg0.key | wg pubkey > /etc/voider/private/wg0.pub");
        run("chmod 600 /etc/voider/private/wg0.key; chmod 644 /etc/voider/private/wg0.pub");
    }
    else if(!fs::exists("/etc/voider/private/wg0.pub")){
        run("cat /etc/voider/private/wg0.key | wg pubkey > /etc/voider/private/wg0.pub");
        run("chmod 644 /etc/voider/private/wg0.pub");
    }
}
static void w1(const std::string&p,const std::string&s,int mode=0600){
    fs::create_directories(fs::path(p).parent_path());
    std::ofstream(p)<<s;
    run("chmod "+std::to_string(mode)+" "+shq(p)+" 2>/dev/null || true");
}
static int valid(const std::string&r,int id){
    return (r=="client"||r=="server")&&id>=2&&id<=254;
}
static std::string dir(const std::string&r,int id){
    return C.mat+"/"+r+"/"+std::to_string(id);
}
static std::string pconf(const std::string&r,int id){
    return (r=="client"?C.pc:C.ps)+"/"+std::to_string(id)+".conf";
}
static std::string addr(const std::string&,int id){
    // For exported clients, this is the client's transport address in the
    // server's single wg0 network. The server itself remains wg0=172.31.0.1.
    return "172.31.0."+std::to_string(id)+"/24";
}
static std::string peeraddr(const std::string&,int){
    // Client bundles must route the server gateway and server call identity.
    // Imported-server bundles must route the remote server gateway/call target.
    return "172.31.0.1/32, 172.29.1.1/32";
}
static int listen_port(const std::string&r,int id){
    // Server role has exactly one shared default-namespace wg0 listener.
    // Imported-server slots may still use per-slot wgX ports.
    return r=="client"?51820:51820+id;
}
static int gen(const std::string&r,int id){
    std::string d=dir(r,id);
    fs::create_directories(d);
    if(r=="client")ensure_server_wg0_key();
    if(!fs::exists(d+"/private.key"))run("wg genkey | tee "+shq(d+"/private.key")+" | wg pubkey > "+shq(d+"/public.key"));
    if(!fs::exists(d+"/preshared.key"))run("wg genpsk > "+shq(d+"/preshared.key"));
    if(!fs::exists(d+"/node.id"))w1(d+"/node.id",r+" "+std::to_string(id)+"\n",0644);
    run("chmod 600 "+shq(d+"/private.key")+" "+shq(d+"/preshared.key")+" 2>/dev/null || true");
    run("chmod 644 "+shq(d+"/public.key")+" 2>/dev/null || true");
    std::string pub=read1(d+"/public.key"),psk=read1(d+"/preshared.key");
    fs::create_directories(fs::path(pconf(r,id)).parent_path());
    std::ofstream f(pconf(r,id));
    f<<"ROLE="<<r<<"\nID="<<id<<"\nPIVPN=0\nWG_OWNED=1\nWG_IF=wg"<<id<<"\nPORT="<<listen_port(r,id)<<"\nTORPORT="<<
    (C.tundup_torport_base+id)<<"\nLOCAL_ADDR="<<addr(r,id)<<"\nPEER_ALLOWED_IP="<<peeraddr(r,id)<<
    "\nPRIVATE_KEY="<<d<<"/private.key\nPUBLIC_KEY="<<pub<<"\nPRESHARED_KEY="<<d<<
    "/preshared.key\nPRESHARED_KEY_VALUE="<<psk<<"\n";
    if(r=="client")f<<"SERVER_PUBLIC_KEY="<<read1("/etc/voider/private/wg0.pub")<<"\n";
    std::ofstream wg(d+"/wg-native.conf");
    wg<<"# generated by voider-peerctl; no PiVPN\n[Interface]\nPrivateKey = "<<read1(d+"/private.key")<<
    "\nAddress = "<<addr(r,id)<<"\nListenPort = "<<listen_port(r,id)<<
    "\n\n# Peer public key is learned from the imported voider bundle.\n# AllowedIPs = "<<
    peeraddr(r,id)<<"\n# PresharedKey = "<<psk<<"\n";
    std::cout<<"PEER_CREATED role="<<r<<" id="<<id<<" pivpn=0 pub="<<pub<<"\n";
    return 0;
}
static int show(const std::string&r,int id){
    std::ifstream f(pconf(r,id));
    std::cout<<f.rdbuf();
    return 0;
}
static int remove_peer(const std::string&r,int id){
    run("rm -rf "+shq(dir(r,id))+" "+shq(pconf(r,id)));
    return 0;
}
int main(int ac,char**av){
    C=cfg();
    if(ac<4){
        std::cerr<<"usage: voider-peerctl create|show|remove ROLE ID\n";
        return 2;
    }
    std::string c=av[1],r=av[2];
    int id=atoi(av[3]);
    if(!valid(r,id))return 3;
    if(c=="create")return gen(r,id);
    if(c=="show")return show(r,id);
    if(c=="remove")return remove_peer(r,id);
    return 2;
}
